### ISSUE TITLE
ここの翻訳の一部が ja .org に反映されてない？

### ISSUE THREAD

**Issue by kurudrive** [jawordpressorg/gutenberg#23]
### Description

公開されてるページ
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-styles/

でおかしい部分があったので修正しようかと思って

https://github.com/jawordpressorg/gutenberg/blob/trunk/docs/reference-guides/block-api/block-styles.md

を見に来たら間違っていないようなので、単純に反映されてないのかなと...
※見てるファイルが違ってたらすみまっせん。

### Step-by-step reproduction instructions

以下見比べる...

公開されてるページ
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-styles/

GitHub上の翻訳
https://github.com/jawordpressorg/gutenberg/blob/trunk/docs/reference-guides/block-api/block-styles.md

### Screenshots, screen recording, code snippet

<img width="2054" alt="スクリーンショット 2022-07-15 1 44 53" src="https://user-images.githubusercontent.com/3272660/179036408-a0ddea26-8a9f-4469-aa7a-0998d60d1399.png">

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by atachibana** [comment]
@kurudrive 

ご推察のとおり、同期が追いついていません...。
https://github.com/WordPress/gutenberg/commit/283ea8d3a519ed67e656980d98e634cece5b6391

しばしお待ちください 🙇

**Comment by atachibana** [comment]
@kurudrive 

他にも同期すべきファイルがあるため、commit は遅れますが、ハンドブックの方は先行して修正しました。
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/block-api/block-styles/

エラーの報告をありがとうございました。

**Comment by kurudrive** [comment]
@atachibana ありがとうございます  (￣人￣)
