### ISSUE TITLE
 Broken link in the Japanese Team Handbook

### ISSUE THREAD

**Issue by qoorus** [jawordpressorg/gutenberg#25]
## What problem does this address?

there are broken links in the below page.
https://ja.wordpress.org/team/handbook/block-editor/getting-started/devenv/

<img width="392" alt="スクリーンショット 2023-12-16 9 36 48" src="https://github.com/jawordpressorg/gutenberg/assets/41640222/a0b5df6c-f230-4d5a-9289-a40e059c4bcd">

## What is your proposed solution?

Please fix them.

**Comment by atachibana** [comment]
Fixed by #26. 
Thank you, @qoorus
